$(document).ready(function(){
    $("#titel1").click(function(){
    	console.log("hoi")
        $("#tekst1").slideToggle("fast");
    });
    $("#titel2").click(function(){
    	console.log("hoi")
        $("#tekst2").slideToggle("fast");
    });
    $("#titel3").click(function(){
    	console.log("hoi")
        $("#tekst3").slideToggle("fast");
    });
    $("#titel4").click(function(){
    	console.log("hoi")
        $("#tekst4").slideToggle("fast");
    });
    $("#titel5").click(function(){
    	console.log("hoi")
        $("#tekst5").slideToggle("fast");
    });
    $("#titel6").click(function(){
    	console.log("hoi")
        $("#tekst6").slideToggle("fast");
    });
    $("#titel7").click(function(){
    	console.log("hoi")
        $("#tekst7").slideToggle("fast");
    });
    $("#titel8").click(function(){
    	console.log("hoi")
        $("#tekst8").slideToggle("fast");
    });
});